---
- name: update apt-get
  apt: update_cache=yes

- name: install fail2ban
  apt: name=fail2ban state=present

- include: ssh_settings.yml
- include: firewall.yml
  when: inventory_hostname != 'default'
