---
- name: add local ssh keys to deploy user
  authorized_key: user={{ deploy_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: disable root user login via ssh
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin no" state=present

- name: allow deploy user login via ssh
  action: lineinfile dest=/etc/ssh/sshd_config insertafter=EOF line="AllowUsers {{ deploy_user }}" state=present
  when: inventory_hostname != 'default'

- name: allow deploy user and vagrant user login via ssh
  action: lineinfile dest=/etc/ssh/sshd_config insertafter=EOF line="AllowUsers {{ deploy_user }} vagrant" state=present
  when: inventory_hostname == 'default'

- name: disable password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no" state=present

- name: restart ssh service
  action: service name=ssh state=restarted

- name: change permissions on authorized_keys
  file: path=/home/{{ deploy_user }}/.ssh/authorized_keys mode=0400
