---
- name: add apt-get repository for latest node
  action: apt_repository repo=ppa:chris-lea/node.js

- name: update apt-get
  apt: update_cache=yes

- name: install node.js
  apt: pkg=nodejs state=present
