---
- name: add apt-get repository for latest nginx
  action: apt_repository repo=ppa:nginx/stable

- name: update apt-get
  apt: update_cache=yes

- name: install nginx
  apt: pkg=nginx state=present

- name: delete default vhost
  action: file path=/etc/nginx/sites-enabled/default state=absent

- name: copy my_app.conf
  template: src=my_app.conf dest=/etc/nginx/sites-enabled/my_app.conf

- name: restart nginx
  action: service name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes
