---
- name: create deploy user
  user: name={{ deploy_user }} shell=/bin/bash

- name: allow deploy user sudo commands without password
  action: lineinfile dest=/etc/sudoers regexp="^root" line="root ALL=(ALL:ALL) ALL\n{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL" state=present
